#!/usr/bin/env python3
"""
Installation script for UV Island Coloring Tool
Supports multiple installation modes and dependency management
"""

import subprocess
import sys
import os
import platform
from pathlib import Path

class DependencyManager:
    """Manage dependencies for UV Island Coloring Tool"""
    
    def __init__(self):
        self.system_info = self.get_system_info()
        self.requirements = self.load_requirements()
    
    def get_system_info(self):
        """Get system information"""
        return {
            'platform': platform.system(),
            'python_version': platform.python_version(),
            'machine': platform.machine(),
            'processor': platform.processor(),
        }
    
    def load_requirements(self):
        """Load requirement specifications"""
        return {
            'core': ['Pillow>=9.0.0', 'numpy>=1.21.0'],
            'fast': ['scipy>=1.9.0'],
            'opencv': ['opencv-python>=4.5.0'],
            'skimage': ['scikit-image>=0.19.0'],
            'all': ['scipy>=1.9.0', 'opencv-python>=4.5.0', 'scikit-image>=0.19.0'],
        }
    
    def check_python_version(self):
        """Check if Python version is compatible"""
        version_tuple = sys.version_info
        if version_tuple.major < 3 or (version_tuple.major == 3 and version_tuple.minor < 8):
            print(f"⚠️  Warning: Python 3.8+ recommended, you have {platform.python_version()}")
            return False
        return True
    
    def check_existing_installation(self):
        """Check what's already installed"""
        installed = {}
        
        packages_to_check = [
            ('PIL', 'Pillow'),
            ('numpy', 'numpy'),
            ('scipy', 'scipy'),
            ('cv2', 'opencv-python'),
            ('skimage', 'scikit-image'),
        ]
        
        for import_name, package_name in packages_to_check:
            try:
                __import__(import_name)
                # Try to get version
                if import_name == 'PIL':
                    from PIL import Image
                    version = Image.__version__
                elif import_name == 'numpy':
                    import numpy
                    version = numpy.__version__
                elif import_name == 'scipy':
                    import scipy
                    version = scipy.__version__
                elif import_name == 'cv2':
                    import cv2
                    version = cv2.__version__
                elif import_name == 'skimage':
                    import skimage
                    version = skimage.__version__
                else:
                    version = "unknown"
                
                installed[package_name] = version
                print(f"✅ {package_name}: {version}")
                
            except ImportError:
                installed[package_name] = None
                print(f"❌ {package_name}: Not installed")
        
        return installed
    
    def create_requirements_file(self, mode='all', output_path='requirements.txt'):
        """Create a requirements.txt file for specific mode"""
        requirements = []
        
        # Always include core
        requirements.extend(self.requirements['core'])
        
        # Add mode-specific requirements
        if mode == 'fast':
            requirements.extend(self.requirements['fast'])
        elif mode == 'opencv':
            requirements.extend(self.requirements['opencv'])
        elif mode == 'skimage':
            requirements.extend(self.requirements['skimage'])
        elif mode == 'all':
            requirements.extend(self.requirements['all'])
        
        # Write to file
        with open(output_path, 'w') as f:
            f.write("# Requirements for UV Island Coloring Tool\n")
            f.write(f"# Mode: {mode}\n")
            f.write("# Generated by install.py\n\n")
            for req in requirements:
                f.write(req + "\n")
        
        print(f"📄 Created requirements file: {output_path}")
        return requirements
    
    def install_packages(self, packages, upgrade=False):
        """Install packages using pip"""
        if not packages:
            print("No packages to install")
            return True
        
        pip_cmd = [sys.executable, "-m", "pip", "install"]
        
        if upgrade:
            pip_cmd.append("--upgrade")
        
        # Add packages
        pip_cmd.extend(packages)
        
        print(f"📦 Installing packages: {', '.join(packages)}")
        print(f"Command: {' '.join(pip_cmd)}")
        
        try:
            result = subprocess.run(
                pip_cmd,
                check=True,
                capture_output=True,
                text=True,
                encoding='utf-8'
            )
            
            if result.stdout:
                print("Installation output:")
                print(result.stdout)
            
            return True
            
        except subprocess.CalledProcessError as e:
            print(f"❌ Installation failed!")
            print(f"Error: {e.stderr}")
            
            # Provide helpful suggestions
            if "opencv-python" in ' '.join(packages) and "win32" in self.system_info['platform'].lower():
                print("\n💡 For Windows OpenCV issues, try:")
                print("   pip install opencv-python-headless")
            
            return False
    
    def create_shortcut(self):
        """Create shortcut/alias for the tool"""
        script_path = os.path.abspath('uv_colorizer.py')
        
        if not os.path.exists('uv_colorizer.py'):
            print("⚠️  Main script not found, cannot create shortcut")
            return
        
        # For Windows
        if self.system_info['platform'] == 'Windows':
            bat_content = f'''@echo off
"{sys.executable}" "{script_path}" %*
'''
            with open('uv_colorizer.bat', 'w') as f:
                f.write(bat_content)
            print("📝 Created Windows batch file: uv_colorizer.bat")
            
            # Also create a PowerShell alias suggestion
            ps_profile = os.path.expanduser('~/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1')
            ps_alias = f'\n# UV Island Coloring Tool alias\nfunction uv-color {{ & "{sys.executable}" "{script_path}" @args }}\n'
            print(f"💡 Add to PowerShell profile ({ps_profile}):")
            print(ps_alias)
        
        # For Unix-like systems
        else:
            # Create shell script
            sh_content = f'''#!/bin/bash
"{sys.executable}" "{script_path}" "$@"
'''
            with open('uv_colorizer.sh', 'w') as f:
                f.write(sh_content)
            
            # Make executable
            os.chmod('uv_colorizer.sh', 0o755)
            print("📝 Created shell script: uv_colorizer.sh")
            
            # Suggest adding to .bashrc or .zshrc
            shell = os.path.basename(os.environ.get('SHELL', 'bash'))
            rc_file = f"~/.{shell}rc"
            alias_cmd = f"alias uv-color='{sys.executable} {script_path}'\n"
            print(f"💡 Add to your shell config ({rc_file}):")
            print(alias_cmd)
    
    def run_verification(self):
        """Run verification script to test installation"""
        verification_script = '''
import sys
try:
    from PIL import Image
    import numpy as np
    print("✅ Pillow and NumPy are working")
    
    # Try to import optional packages
    try:
        import scipy
        print("✅ SciPy is available")
    except ImportError:
        print("⚠️  SciPy not available (fast mode won't work)")
    
    try:
        import cv2
        print("✅ OpenCV is available")
    except ImportError:
        print("⚠️  OpenCV not available (opencv mode won't work)")
    
    try:
        import skimage
        print("✅ scikit-image is available")
    except ImportError:
        print("⚠️  scikit-image not available (skimage mode won't work)")
    
    # Test image creation
    test_img = Image.new('RGBA', (100, 100), (255, 0, 0, 128))
    print("✅ Test image creation successful")
    
    print("\\n🎉 All checks passed! You can now use the UV Island Coloring Tool.")
    
except Exception as e:
    print(f"❌ Verification failed: {e}")
    sys.exit(1)
'''
        
        print("🔍 Running verification...")
        try:
            result = subprocess.run(
                [sys.executable, "-c", verification_script],
                check=True,
                capture_output=True,
                text=True
            )
            print(result.stdout)
            return True
        except subprocess.CalledProcessError as e:
            print("Verification failed:")
            print(e.stderr)
            return False

def print_banner():
    """Print installation banner"""
    banner = """
╔══════════════════════════════════════════════════════════╗
║      UV Island Coloring Tool - Installation Script       ║
╚══════════════════════════════════════════════════════════╝
"""
    print(banner)

def print_help():
    """Print help information"""
    help_text = """
Usage:
  python install.py [mode] [options]

Modes:
  minimal    - Install only core dependencies (Pillow + NumPy)
  fast       - Install core + SciPy (original fast mode)
  opencv     - Install core + OpenCV (fastest mode)
  skimage    - Install core + scikit-image
  all        - Install all dependencies (recommended)
  verify     - Check current installation
  help       - Show this help message

Options:
  --upgrade  - Upgrade existing packages
  --shortcut - Create shortcut/alias
  --clean    - Create clean requirements.txt file

Examples:
  python install.py all
  python install.py fast --upgrade
  python install.py opencv --shortcut
  python install.py verify

Note: The tool works with Python 3.8+. Python 3.10+ recommended.
"""
    print(help_text)

def main():
    """Main installation function"""
    print_banner()
    
    # Parse command line arguments
    args = sys.argv[1:]
    mode = 'all'  # Default mode
    upgrade = False
    create_shortcut = False
    clean_requirements = False
    
    if not args:
        print("No mode specified, using default mode: all")
        print("Use 'python install.py help' for usage information\n")
    else:
        valid_modes = ['minimal', 'fast', 'opencv', 'skimage', 'all', 'verify', 'help']
        
        for arg in args:
            if arg in valid_modes:
                mode = arg
            elif arg == '--upgrade':
                upgrade = True
            elif arg == '--shortcut':
                create_shortcut = True
            elif arg == '--clean':
                clean_requirements = True
            elif arg == '--help' or arg == '-h':
                print_help()
                return
    
    if mode == 'help':
        print_help()
        return
    
    # Initialize dependency manager
    manager = DependencyManager()
    
    # Check Python version
    print("🔍 Checking Python version...")
    if not manager.check_python_version():
        print("⚠️  Python version check failed, continuing anyway...")
    
    # Print system info
    print(f"\n📊 System Information:")
    for key, value in manager.system_info.items():
        print(f"  {key}: {value}")
    
    if mode == 'verify':
        print("\n🔍 Checking existing installation...")
        manager.check_existing_installation()
        print("\n✅ Verification complete")
        return
    
    print(f"\n🎯 Installation Mode: {mode.upper()}")
    
    # Check existing installation first
    print("\n🔍 Checking existing packages...")
    installed = manager.check_existing_installation()
    
    # Determine packages to install
    packages_to_install = []
    
    # Always check core packages
    core_packages = ['Pillow', 'numpy']
    for pkg in core_packages:
        if installed.get(pkg) is None:
            packages_to_install.extend(manager.requirements['core'])
            break
    
    # Add mode-specific packages
    if mode == 'fast':
        if installed.get('scipy') is None:
            packages_to_install.extend(manager.requirements['fast'])
    elif mode == 'opencv':
        if installed.get('opencv-python') is None:
            packages_to_install.extend(manager.requirements['opencv'])
    elif mode == 'skimage':
        if installed.get('scikit-image') is None:
            packages_to_install.extend(manager.requirements['skimage'])
    elif mode == 'all':
        for pkg in ['scipy', 'opencv-python', 'scikit-image']:
            if installed.get(pkg) is None:
                packages_to_install.extend(manager.requirements['all'])
                break
    
    # Remove duplicates
    packages_to_install = list(set(packages_to_install))
    
    if not packages_to_install and not upgrade:
        print("\n✅ All required packages are already installed!")
        print("   Use --upgrade to update existing packages")
    else:
        if upgrade:
            print("\n⬆️  Upgrading existing packages...")
            # Upgrade all packages for the mode
            if mode == 'minimal':
                upgrade_packages = manager.requirements['core']
            elif mode == 'fast':
                upgrade_packages = manager.requirements['core'] + manager.requirements['fast']
            elif mode == 'opencv':
                upgrade_packages = manager.requirements['core'] + manager.requirements['opencv']
            elif mode == 'skimage':
                upgrade_packages = manager.requirements['core'] + manager.requirements['skimage']
            elif mode == 'all':
                upgrade_packages = manager.requirements['core'] + manager.requirements['all']
            
            success = manager.install_packages(upgrade_packages, upgrade=True)
        else:
            print(f"\n📦 Packages to install: {', '.join(packages_to_install) if packages_to_install else 'None'}")
            if packages_to_install:
                success = manager.install_packages(packages_to_install)
            else:
                success = True
        
        if not success:
            print("\n❌ Installation failed!")
            return
    
    # Create requirements file if requested
    if clean_requirements:
        manager.create_requirements_file(mode)
    
    # Create shortcut if requested
    if create_shortcut:
        print("\n🔗 Creating shortcut...")
        manager.create_shortcut()
    
    # Run verification
    print("\n🔍 Running final verification...")
    verification_success = manager.run_verification()
    
    # Print completion message
    print("\n" + "="*60)
    if verification_success:
        print("🎉 INSTALLATION COMPLETED SUCCESSFULLY!")
        print("\n📋 Quick Start Guide:")
        print("   1. Run the tool: python uv_colorizer.py input.png output.png")
        print("   2. Use --help to see all options: python uv_colorizer.py --help")
        print("   3. Try different modes: --mode fast/complex/opencv/skimage")
        
        if mode in ['opencv', 'all']:
            print("\n💡 OpenCV mode is available (fastest):")
            print("   python uv_colorizer.py input.png output.png --mode opencv")
        
        if mode in ['fast', 'all']:
            print("\n💡 Fast mode is available (requires SciPy):")
            print("   python uv_colorizer.py input.png output.png --mode fast")
        
        print("\n📚 For more information, see the README or run:")
        print("   python uv_colorizer.py --help")
    else:
        print("⚠️  Installation completed with warnings")
        print("   Some features may not work correctly")
    
    print("="*60)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n⚠️  Installation interrupted by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        sys.exit(1)